# Generated by Django 6.0.2 on 2026-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='obra_entrega_prevista',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
