# Generated by Django 6.0.2 on 2026-03-02 12:31

import deals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('stage', models.CharField(choices=[('LEAD', 'Lead'), ('CONTATO', 'Contato'), ('PROPOSTA', 'Proposta'), ('NEGOCIACAO', 'Negociação'), ('FECHADO_GANHO', 'Fechado (Ganho)'), ('PERDIDO', 'Perdido'), ('PAUSADO', 'Pausado')], default='LEAD', max_length=20)),
                ('elevador_entrega_prevista', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tem_permuta', models.BooleanField(default=False)),
                ('permuta_tipo', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_elevador', models.CharField(blank=True, default='', max_length=120)),
                ('paradas', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade_elevadores', models.PositiveIntegerField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('next_action_note', models.CharField(blank=True, default='', max_length=220)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VISITA', 'Visita'), ('WHATSAPP', 'WhatsApp'), ('LIGACAO', 'Ligação'), ('REUNIAO', 'Reunião'), ('EMAIL', 'E-mail'), ('TAREFA', 'Tarefa')], max_length=20)),
                ('status', models.CharField(choices=[('DONE', 'Feito'), ('PENDING', 'Pendente'), ('CANCELED', 'Cancelado')], default='DONE', max_length=20)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='DealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PROPOSTA', 'Proposta'), ('CONTRATO', 'Contrato'), ('MEMORIAL', 'Memorial'), ('OUTRO', 'Outro')], default='PROPOSTA', max_length=20)),
                ('version_label', models.CharField(blank=True, default='', max_length=20)),
                ('file', models.FileField(upload_to=deals.models.deal_attachment_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='DealBarterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=220)),
                ('kind', models.CharField(blank=True, default='APARTAMENTO', max_length=60)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barter_items', to='deals.deal')),
            ],
        ),
    ]
