# Generated by Django 6.0.2 on 2026-03-02 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviada'), ('ACCEPTED', 'Aceita'), ('REJECTED', 'Recusada')], default='DRAFT', max_length=20)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tem_permuta', models.BooleanField(default=False)),
                ('valor_permuta', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('permuta_tipo', models.CharField(blank=True, default='', max_length=20)),
                ('obra_entrega_prevista', models.DateField(blank=True, null=True)),
                ('elevador_entrega_prevista', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='deals.deal')),
            ],
        ),
    ]
