# Generated by Django 6.0.2 on 2026-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_proposal'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='proposals', to='projects.project'),
        ),
    ]
