# Generated by Django 6.0.2 on 2026-03-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_proposal_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='occurred_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('DONE', 'Feito'), ('PENDING', 'Pendente'), ('CANCELED', 'Cancelado')], db_index=True, default='DONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('VISITA', 'Visita'), ('WHATSAPP', 'WhatsApp'), ('LIGACAO', 'Ligação'), ('REUNIAO', 'Reunião'), ('EMAIL', 'E-mail'), ('TAREFA', 'Tarefa')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='next_action_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('CONTATO', 'Contato'), ('PROPOSTA', 'Proposta'), ('NEGOCIACAO', 'Negociação'), ('FECHADO_GANHO', 'Fechado (Ganho)'), ('PERDIDO', 'Perdido'), ('PAUSADO', 'Pausado')], db_index=True, default='LEAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dealattachment',
            name='type',
            field=models.CharField(choices=[('PROPOSTA', 'Proposta'), ('CONTRATO', 'Contrato'), ('MEMORIAL', 'Memorial'), ('OUTRO', 'Outro')], db_index=True, default='PROPOSTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='dealbarteritem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviada'), ('ACCEPTED', 'Aceita'), ('REJECTED', 'Recusada')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
