# Generated by Django 6.0.2 on 2026-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_activity_created_at_alter_activity_occurred_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='elevador_entrega_prevista',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='obra_entrega_prevista',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
