# Generated by Django 6.0.2 on 2026-03-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_proposal_elevador_entrega_prevista_and_more'),
        ('projects', '0002_alter_project_obra_entrega_prevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='multi_deals', to='projects.project'),
        ),
    ]
