# Generated by Django 6.0.2 on 2026-03-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_deal_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealattachment',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='deals.proposal'),
        ),
    ]
